package com.example.nextgen.offline;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// Simple Room entity to hold a locally saved submission pending upload
@Entity(tableName = "pending_submissions")
public class PendingSubmission {
    @PrimaryKey
    @NonNull
    public String clientSubmissionId; // UUID generated by client

    public String examId;
    public String studentId; // the DB key used in Scores/ExamStudents
    public String answersJson; // JSON string with student's answers
    public int computedScore;
    public int maxScore;
    public long timestamp;
    public String status; // "PENDING", "SYNCING", "SYNCED", "FAILED"
}