package com.finale.nextgen.offline;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * PendingSubmission stored in Room for offline submissions.
 * Added metadata fields so dashboard can show useful info while offline.
 */
@Entity(tableName = "pending_submissions",
        indices = {@Index(value = {"examId", "studentId"})})
public class PendingSubmission {
    @PrimaryKey
    @NonNull
    public String clientSubmissionId; // UUID generated by client

    public String examId;
    public String studentId; // the DB key used in Scores/ExamStudents
    public String answersJson;
    public int computedScore;
    public int maxScore;
    public long timestamp;
    public String status;

    // Optional metadata to improve offline UX
    public String studentName;
    public String profileImage; // base64 or URL (nullable)
    public String subjectName;
    public String teacherName;
    public String subjectCode;

    // Use primitive with default 0 to match migration that adds NOT NULL DEFAULT 0
    public int deductions = 0;
}